description: LLM HumanEval
category_id: 1
node_id: 2
family_id: 0
script: core/llm/eval.py
cmd: python core/llm/eval.py humaneval --model_name llama
outputs:
  result:
    description: Evaluation results
    title: Result
    type: string
properties:
  model_path:
    description: Model to be evaluated
    title: Model
    type: 6
  n_sample:
    default: 1
    description: Number of samples to generate per prompt
    title: N Samples
    type: integer
  load_8bit:
    default: true
    description: Use 8-bit precision
    title: Load 8bit
    type: boolean
